name: bangladesh_admin_map
description: BD administrative map drilldown with persons list

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/CountryMap.json
    - assets/divisions_geo.json
    - assets/districts_geo.json
    - assets/upazilas_geo.json
    - assets/unions_geo.json
    - assets/persons.json
